var urlToMonitor = [
{batchName:"RM1",brand :"Royal Mail",app:"Send ",url:"https://www.royalmail.com/sending"},
{batchName:"RM1",brand :"Royal Mail",app:"Artwork - PPI",url:"https://www.royalmail.com/produce-ppi"},
{batchName:"RM1",brand :"Royal Mail",app:"Artwork - RSO",url:"https://www.royalmail.com/response-services-artwork-generator/licence/"},
{batchName:"RM1",brand :"Royal Mail",app:"Artwork - BMA",url:"https://www.royalmail.com/business-mail-advanced-artwork-generator/licence/"},
{batchName:"RM1",brand :"Royal Mail",app:"Track Return",url:"https://www.royalmail.com/track-my-return/pick-a-retailer"},
{batchName:"RM1",brand :"Royal Mail",app:"HomePage",url:"https://www.royalmail.com/"},
{batchName:"RM1",brand :"Royal Mail",app:"RMG Business HomePage",url:"https://www.royalmail.com/business"},
{batchName:"RM1",brand :"Royal Mail",app:"RMG Business",url:"https://www.royalmail.com/business/manage-mail/po-box"},
{batchName:"RM1",brand :"Royal Mail",app:"RMG Business",url:"https://www.royalmail.com/business/shipping/ways-pay/click-drop"},
{batchName:"RM1",brand :"Royal Mail",app:"RMG Business",url:"https://www.royalmail.com/business/shipping/ways-pay/online-business-account"},
{batchName:"RM1",brand :"Royal Mail",app:"RMG OBA",url:"https://www.royalmail.com/discounts-payment/credit-account/online-business-account"},
{batchName:"RM1",brand :"Royal Mail",app:"Redirection D6",url:"https://www.royalmail.com/personal/receiving-mail/redirection"},
{batchName:"RM1",brand :"Royal Mail",app:"Redirection Renewal D6",url:"https://www.royalmail.com/personal/receiving-mail/redirection/renewal"},
{batchName:"RM1",brand :"Royal Mail",app:"Price Finder",url:"https://www.royalmail.com/price-finder"},
{batchName:"RM2",brand :"Royal Mail",app:"KeepSafe D6",url:"https://www.royalmail.com/receiving/keepsafe"},
{batchName:"RM2",brand :"Royal Mail",app:"PO BOX D6",url:"https://www.royalmail.com/receiving/po-box"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Registration D8",url:"https://www.royalmail.com/register"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Login D8",url:"https://www.royalmail.com/login"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Business Login D8",url:"https://www.royalmail.com/business/login"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Login D8",url:"https://www.royalmail.com/user/login"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Business Login D8",url:"https://www.royalmail.com/business/user/login"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Pay a fee D8",url:"https://www.royalmail.com/receiving-mail/pay-a-fee"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Pay a fee D8",url:"https://www.royalmail.com/receiving-mail/pay-a-fee/pay"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Redelivery D8",url:"https://www.royalmail.com/receiving-mail/redelivery"},
{batchName:"RM2",brand :"Royal Mail - D8",app:"Redelivery D8",url:"https://www.royalmail.com/receiving-mail/redelivery/book"},
{batchName:"RM3",brand :"Royal Mail - D8",app:"Find a Postcode D8",url:"https://www.royalmail.com/find-a-postcode"},
{batchName:"RM3",brand :"Royal Mail - D8",app:"Services Near You D8",url:"https://www.royalmail.com/services-near-you"},
{batchName:"RM3",brand :"Royal Mail",app:"SSO",url:"https://idp.royalmailgroup.com/"},
{batchName:"RM3",brand :"Royal Mail - D8",app:"Track and Trace",url:"https://www.royalmail.com/track-your-item"},
{batchName:"RM3",brand :"Royal Mail - D8",app:"Track and Trace",url:"https://www.royalmail.com/track-your-item%23/proof-of-delivery?data=%7B%22trackingNumber%22%3A%22NV365486236GB%22%2C%22summaryText%22%3A%22Your%20item%20was%20delivered%20on%20**01-09-2020**.%20%22%2C%22imageUrl%22%3A%22blob%3Ahttps%3A%2F%2Fwww.royalmail.com%2F986449f5-55c7-4e61-a077-05b6c37188d0%22%2C%22imageRotationDegrees%22%3A0%2C%22marginTop%22%3A0%2C%22marginBottom%22%3A0%2C%22recipientName%22%3A%22KP%20BN%22%2C%22productName%22%3A%22Royal%20Mail%20Signed%20For%E2%84%A2%22%2C%22deliveryDate%22%3A%2200%3A55%2C%20Tuesday%2001%20September%202020%22%7D"},
{batchName:"RM3",brand :"Royal Mail - D8",app:"Pay a fee D8",url:"https://www.royalmail.com/receiving-mail/redelivery/book%23/details-from-your-card"},
{batchName:"RM3",brand :"Royal Mail - D8",app:"Pay a fee D8",url:"https://www.royalmail.com/receiving-mail/pay-a-fee/pay%23/card-details"},
{batchName:"RM3",brand :"Royal Mail - Content Pages",app:"Send - International",url:"https://www.royalmail.com/sending/international/country-guides/usa"},
{batchName:"RM3",brand :"Royal Mail - Content Pages",app:"Send - International",url:"https://www.royalmail.com/sending/international/international-standard"},
{batchName:"RM3",brand :"Royal Mail - Content Pages",app:"Send - International",url:"https://www.royalmail.com/sending/international/international-tracked-signed"},
{batchName:"RM3",brand :"Royal Mail - Content Pages",app:"Send - Stamps",url:"https://www.royalmail.com/sending/stamps"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"Send - Stamps",url:"https://www.royalmail.com/sending/uk/1st-class"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"Send - Stamps",url:"https://www.royalmail.com/sending/uk/2nd-class"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"Send - Stamps",url:"https://www.royalmail.com/sending/uk/special-delivery-guaranteed-1pm"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"RMG Collection",url:"https://www.royalmail.com/collection"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"RMG Postage Prices",url:"https://www.royalmail.com/current-postage-prices"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"D8 Help",url:"https://www.royalmail.com/d8/help/redirection"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"Priority PostBoxes",url:"https://www.royalmail.com/priority-postboxes"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"Help",url:"https://personal.help.royalmail.com/app/answers/detail/a_id/6905/~/what-email-%2F-text-%2F-facebook-message-"},
//{batchName:"RM3",brand :"Royal Mail - Content Pages",app:"Help",url:"https://personal.help.royalmail.com/app/answers/detail/a_id/89/~/size-and-weight-guide-%E2%80%93-uk-letters-"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"Help",url:"https://personal.help.royalmail.com/app/contact"},
{batchName:"Others",brand :"Click and Drop",app:"Send Item",url:"https://send.royalmail.com/"},
{batchName:"Others",brand :"Royal Mail - Content Pages",app:"Help",url:"https://personal.help.royalmail.com/app/answers/detail/a_id/5346/~/service-update---public-holidays"},
{batchName:"Saver",brand :"Click and Drop",app:"Send Item",url:"https://send.royalmail.com/collect/youritems"},
{batchName:"Saver",brand :"Click and Drop",app:"Send Item",url:"https://send.royalmail.com/send/youritem"},
{batchName:"Saver",brand :"RM Shop",app:"HomePage",url:"https://shop.royalmail.com/"},
{batchName:"Saver",brand :"RM Shop",app:"Shop Stamps",url:"https://shop.royalmail.com/postage-and-packaging/first-and-second-class-stamps"},
{batchName:"Saver",brand :"RM Shop",app:"Shop Stamps",url:"https://shop.royalmail.com/postage-and-packaging/stamp-sheets"},
{batchName:"Saver",brand :"RM Shop",app:"Shop Stamps",url:"https://shop.royalmail.com/special-stamp-issues"},
{batchName:"Saver",brand :"RM Shop",app:"Shop Stamps",url:"https://shop.royalmail.com/special-stamp-issues/only-fools-and-horses"},
{batchName:"Saver",brand :"RM Shop",app:"Shop Stamps",url:"https://shop.royalmail.com/stamps-signup"},
{batchName:"Saver",brand :"Click and Drop",app:"Send Parcel",url:"https://parcel.royalmail.com/"},
{batchName:"Saver",brand :"Royal Mail",app:"Redirection D6",url:"https://www.royalmail.com/start-your-redirection"},
{batchName:"Sweeper",brand :"Royal Mail",app:"Redirection D6",url:"https://www.royalmail.com/start-your-redirection-p2"},
{batchName:"Sweeper",brand :"Royal Mail",app:"SSO",url:"https://idp.royalmailgroup.com/opensso/XUI/?goto=https://www.royalmail.com%23login/"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"Worldwide Directory",url:"https://www.parcelforce.com/worldwide-directory"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"Worldwide Directory",url:"https://www.parcelforce.com/worldwide-directory/usa?account=0"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"PFW Track and Trace",url:"https://www.parcelforce.com/track-trace"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"PFW HomePage",url:"https://www.parcelforce.com/"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"PFW Receiving",url:"https://www.parcelforce.com/receiving/parcel-delivery"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"PFW Help",url:"https://www.parcelforce.com/help-and-advice"},
//{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW Send",url:"https://send.parcelforce.com/"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"PFW Redelivery",url:"https://www.parcelforce.com/redelivery"},
{batchName:"Sweeper",brand :"Parcelforce Worldwide",app:"PFW Send",url:"https://www.parcelforce.com/sending-parcel"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW Custom Charges",url:"https://www.parcelforce.com/receiving/customs-charge"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW Depot Finder",url:"https://www.parcelforce.com/depot-finder"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW Postcode Finder",url:"https://www.parcelforce.com/postcode-finder"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW Parcel Delivery",url:"https://www.parcelforce.com/sending-parcel/parcel-delivery"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW BranchFinder",url:"https://www.parcelforce.com/branch-finder"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW Courier Service",url:"https://www.parcelforce.com/sending-parcel/courier-services"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW International Parcel Delivery",url:"https://www.parcelforce.com/sending-parcel/international-parcel-delivery"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"PFW Business Parcels",url:"https://www.parcelforce.com/business-parcels"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"Login",url:"https://www.parcelforce.com/user/login"},
{batchName:"PFW",brand :"Parcelforce Worldwide",app:"Registration",url:"https://www.parcelforce.com/user/register"},
];

